### ISSUE TITLE
__init__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by e-minguez** [algirdasc/xiaomi-ble-mqtt#13]
```
Traceback (most recent call last):
  File "/usr/src/app/data-read.py", line 29, in <module>
    poller = MiTempBtPoller(mac, BluepyBackend, ble_timeout=config[device].getint("timeout", 10))
  File "/usr/src/app/mitemp/mitemp_bt/mitemp_bt_poller.py", line 34, in __init__
    self._bt_interface = BluetoothInterface(backend, adapter)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

**Comment by algirdasc** [comment]
Fixed in latest commit.
