### ISSUE TITLE
When adding more than 1 device, it crashes

### ISSUE THREAD

**Issue by jsponz** [algirdasc/xiaomi-ble-mqtt#2]
Hi, 

I have tested with 1 device, it works perfectly. 

I have tested with 2 devices and it crashes (content of "xiaomi-ble.log"):

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/btlewrap/bluepy.py", line 26, in _func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/btlewrap/bluepy.py", line 55, in connect
    self._peripheral = Peripheral(mac, iface=iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 58:2D:34:32:D5:BD, addr type: public

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/xiaomi-ble-mqtt/data-read.py", line 48, in <module>
    temperature = poller.parameter_value(MI_TEMPERATURE)
  File "/usr/local/lib/python3.5/dist-packages/mitemp_bt/mitemp_bt_poller.py", line 125, in parameter_value
    self.fill_cache()
  File "/usr/local/lib/python3.5/dist-packages/mitemp_bt/mitemp_bt_poller.py", line 59, in fill_cache
    self.firmware_version()
  File "/usr/local/lib/python3.5/dist-packages/mitemp_bt/mitemp_bt_poller.py", line 89, in firmware_version
    with self._bt_interface.connect(self._mac) as connection:
  File "/usr/local/lib/python3.5/dist-packages/btlewrap/base.py", line 44, in __enter__
    self._backend.connect(self._mac)
  File "/usr/local/lib/python3.5/dist-packages/btlewrap/bluepy.py", line 32, in _func_wrapper
    raise BluetoothBackendException() from last_error
btlewrap.base.BluetoothBackendException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/xiaomi-ble-mqtt/data-read.py", line 102, in <module>
    except bluepy.btle.BTLEException:
NameError: name 'bluepy' is not defined

Content of "devices.ini":

[living_room]
device_mac=58:2D:34:32:D5:BD
topic=ble/living
average=3

[bad]
device_mac=58:2D:34:32:D5:2E
topic=ble/bad
average=3

Any help? 

Thanks!

**Comment by algirdasc** [comment]
Hi,
Seems like your device is unreachable. Try bringing closer to your BT receiver.

**Comment by jsponz** [comment]
Hi, Thanks for quick reply. 

Both devices are 30 cm from each other... 

Does it need to release the BT in order to connect to the second one?

**Comment by algirdasc** [comment]
No, it does not need to release BT. Just make sure BT device is not used by other software. Could you double check device mac address? By "30 cm from each other" you mean distance between devices or BT receiver?

**Comment by jsponz** [comment]
By "30 cm..." I mean the distance between devices (Xiaomi devices). 

As far as I know, there is no other software using the BT. With one device, it works. When adding the second one, it fails...

**Comment by algirdasc** [comment]
Could you try bringing failing device closer to BT receiver? When trying one device does it works with both devices?

**Comment by jsponz** [comment]
Same result. 

As soon as there is 2 or more devices in devices.ini I get the message. 

Only the first device is processed.

**Comment by jsponz** [comment]
With your updated code, the two devices are read :-) 

But on the log, I still get:

Traceback (most recent call last):
  File "/home/pi/xiaomi-ble-mqtt/data-read.py", line 103, in <module>
    mqtt_client.publish(config[device].get("availability_topic"), "online")
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 1129, in publish
    raise ValueError('Invalid topic.')
ValueError: Invalid topic.
Traceback (most recent call last):
  File "/home/pi/xiaomi-ble-mqtt/data-read.py", line 103, in <module>
    mqtt_client.publish(config[device].get("availability_topic"), "online")
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 1129, in publish
    raise ValueError('Invalid topic.')
ValueError: Invalid topic.
2019-06-28 16:16:06.848219 bath_room  :  {"temperature": 27.6, "battery": 100, "humidity": 52.1}
Error polling device bath_room:
None
2019-06-28 16:16:11.921847 living_room  :  {"temperature": 27.2, "battery": 94, "humidity": 52.5}
Error polling device living_room:
None

**Comment by algirdasc** [comment]
Could you please pull latest commit and try again?

**Comment by jsponz** [comment]
Testing... Thanks!

**Comment by jsponz** [comment]
Much better! Great!

I have 3 devices connected to my Raspberry Pi. Let's the battery life (I am getting a value every 15 minutes).
