### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by pristis** [algirdasc/xiaomi-ble-mqtt#20]
Hello!

When I try to run  `python3 data-read.py`, I see this in the console:

`Traceback (most recent call last):
  File "data-read.py", line 3, in <module>
    from mitemp.mitemp_bt.mitemp_bt_poller import MiTempBtPoller
  File "/home/pi/xiaomi-ble-mqtt/mitemp/mitemp_bt/mitemp_bt_poller.py", line 8, in <module>
    from btlewrap.base import BluetoothInterface, BluetoothBackendException
  File "/home/pi/.local/lib/python3.5/site-packages/btlewrap/__init__.py", line 23, in <module>
    from btlewrap.gatttool import (
  File "/home/pi/.local/lib/python3.5/site-packages/btlewrap/gatttool.py", line 44
    ):
    ^
SyntaxError: invalid syntax
`

Any help will be great. Thanks for your time!

**Comment by pristis** [comment]
not relevant
