### ISSUE TITLE
Problem on another device

### ISSUE THREAD

**Issue by jsponz** [algirdasc/xiaomi-ble-mqtt#6]
Hi again, 

I have installed your script on another device with an external BT dongle and with the same configuration (for devices), I get the following error: 

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/btlewrap/bluepy.py", line 26, in _func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/btlewrap/bluepy.py", line 55, in connect
    self._peripheral = Peripheral(mac, iface=iface)
  File "/btle.py", line 391, in __init__
  File "/btle.py", line 439, in _connect
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 58:2D:34:32:D5:2E, addr type: public

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "data-read.py", line 49, in <module>
    temperature = poller.parameter_value(MI_TEMPERATURE)
  File "/usr/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 125, in parameter_value
    self.fill_cache()
  File "/usr/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 59, in fill_cache
    self.firmware_version()
  File "/usr/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 89, in firmware_version
    with self._bt_interface.connect(self._mac) as connection:
  File "/usr/lib/python3.7/site-packages/btlewrap/base.py", line 44, in __enter__
    self._backend.connect(self._mac)
  File "/usr/lib/python3.7/site-packages/btlewrap/bluepy.py", line 32, in _func_wrapper
    raise BluetoothBackendException() from last_error
btlewrap.base.BluetoothBackendException
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/btlewrap/bluepy.py", line 26, in _func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/btlewrap/bluepy.py", line 55, in connect
    self._peripheral = Peripheral(mac, iface=iface)
  File "/btle.py", line 391, in __init__
  File "/btle.py", line 439, in _connect
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 58:2D:34:32:D5:BD, addr type: public

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "data-read.py", line 49, in <module>
    temperature = poller.parameter_value(MI_TEMPERATURE)
  File "/usr/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 125, in parameter_value
    self.fill_cache()
  File "/usr/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 59, in fill_cache
    self.firmware_version()
  File "/usr/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 89, in firmware_version
    with self._bt_interface.connect(self._mac) as connection:
  File "/usr/lib/python3.7/site-packages/btlewrap/base.py", line 44, in __enter__
    self._backend.connect(self._mac)
  File "/usr/lib/python3.7/site-packages/btlewrap/bluepy.py", line 32, in _func_wrapper
    raise BluetoothBackendException() from last_error
btlewrap.base.BluetoothBackendException
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/btlewrap/bluepy.py", line 26, in _func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/btlewrap/bluepy.py", line 55, in connect
    self._peripheral = Peripheral(mac, iface=iface)
  File "/btle.py", line 391, in __init__
  File "/btle.py", line 439, in _connect
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 58:2D:34:32:D4:C4, addr type: public

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "data-read.py", line 49, in <module>
    temperature = poller.parameter_value(MI_TEMPERATURE)
  File "/usr/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 125, in parameter_value
    self.fill_cache()
  File "/usr/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 59, in fill_cache
    self.firmware_version()
  File "/usr/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 89, in firmware_version
    with self._bt_interface.connect(self._mac) as connection:
  File "/usr/lib/python3.7/site-packages/btlewrap/base.py", line 44, in __enter__
    self._backend.connect(self._mac)
  File "/usr/lib/python3.7/site-packages/btlewrap/bluepy.py", line 32, in _func_wrapper
    raise BluetoothBackendException() from last_error
btlewrap.base.BluetoothBackendException
Error polling device bath_room: 
None
Error polling device living_room: 
None
Error polling device nicolas_room: 
None

Any help? 

Thanks!
Jorge

**Comment by jsponz** [comment]
Any help on this? 

Thanks!

**Comment by algirdasc** [comment]
Hey, sorry, I've spent two weeks on vacation. Generally, error
```bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 58:2D:34:32:D4:C4, addr type: public```
means that software could not connect to device due some fault - out of range, device is not connected. Firstly I'll suggest bringing device closer to receiver to test.

**Comment by jsponz** [comment]
Thanks for your answer. Device is 30 cm away from the BT. 

Any other idea? :-)
