### ISSUE TITLE
Problem with btlewrap.base

### ISSUE THREAD

**Issue by bogdanriciu** [algirdasc/xiaomi-ble-mqtt#9]
Hello
I dont see to work the code 
I try to put all the code in all of the folders 
Python version 
Raspbery PI 3b+ With Raspberian

>>> 
`Traceback (most recent call last):
  File "/home/pi/mitemp/data-read.py", line 2, in <module>
    from mitemp.mitemp_bt.mitemp_bt_poller import MiTempBtPoller
  File "/home/pi/mitemp/mitemp/mitemp_bt/mitemp_bt_poller.py", line 8, in <module>
    from btlewrap.base import BluetoothInterface, BluetoothBackendException
ImportError: No module named 'btlewrap.base'
>>> 
`

**Comment by bogdanriciu** [comment]
Sorry . I have instal a fresh Raspberian and works 
Thanks
